#  This play is used to add the users and grant them with certain roles
---
- hosts: localhost
  gather_facts: no
  vars_files:
  - "{{ playbook_dir }}/vars/external_vars.yaml"
  module_defaults:
    group/k8s:
      kubeconfig: "{{ kubeconfig_file }}"

  tasks:
  - include_vars: "{{ playbook_dir }}/vars/k8s_login.yaml"

  - name: Retrieve htpasswd-secret
    k8s_info:
      api_version: v1
      kind: Secret
      name: "{{ secret_htpasswd }}"
      namespace: openshift-config
    register: output_secret

  - name: Save contents to a file
    copy:
      content: "{{ output_secret.resources[0].data.htpasswd | b64decode }}"
      dest: "{{ users_htpasswd }}"

  - name: Add users to the HTPasswd file
    htpasswd:
      path: "{{ users_htpasswd }}"
      name: "{{ item.user }}"
      password: "{{ item.password }}"
    loop:
      - "{{ k8s_smcp_admin }}"
      - "{{ k8s_bookinfo_admin }}"

  - name: Replace htpasswd-secret with updated file
    k8s:
      state: present
      definition: 
        apiVersion: v1
        kind: Secret
        type: Opaque
        metadata:
          name: "{{ secret_htpasswd }}"
          namespace: openshift-config
        data:
          htpasswd: "{{ lookup('file',users_htpasswd) | b64encode }}"
