---
- hosts: localhost
  gather_facts: no

  tasks:
  - include_vars: "{{ playbook_dir }}/vars/k8s_login.yaml"

  - name: Retrieve HTPasswd file
    command: >
      oc get secret htpass-secret -ojsonpath={.data.htpasswd}
      -n openshift-config | base64 -d > {{ users_htpasswd }}

  - name: Add users to the HTPasswd file
    htpasswd:
      path: "{{ users_htpasswd }}"
      name: "{{ item.user }}"
      password: "{{ item.password }}"
    loop:
      - "{{ smcp_admin }}"
      - "{{ bookinfo_admin }}"

  - name: Replace htpasswd-secret with updated file
    k8s:
      state: present
      definition: 
        apiVersion: v1
        kind: Secret
        type: Opaque
        metadata:
          name: htpasswd-secret
          namespace: openshift-config
        data:
          htpasswd: "{{ users_htpasswd }}"

