---
- hosts: localhost
  gather_facts: no
  vars_files:
  - "{{ playbook_dir }}/vars/external_vars.yaml"

  tasks:
  - include_vars: "{{ playbook_dir }}/vars/k8s_login.yaml"

  - name: Retrieve HTPasswd file
    shell: >
      oc get secret htpass-secret -ojsonpath={.data.htpasswd}
      -n openshift-config | base64 -d > {{ users_htpasswd }}

  - name: Add users to the HTPasswd file
    htpasswd:
      path: "{{ users_htpasswd }}"
      name: "{{ item.user }}"
      password: "{{ item.password }}"
    loop:
      - "{{ smcp_admin }}"
      - "{{ bookinfo_admin }}"

  - name: Log in to OpenShift
    k8s_auth:
      host: "{{ api_url }}"
      ca_cert: "{{ api_cert }}"
      username: "{{ k8s_admin }}"
      password: "{{ k8s_admin_password }}"
    register: k8s_auth_result

  - name: Replace htpasswd-secret with updated file
    k8s:
      apply: yes
      state: present
      definition: 
        apiVersion: v1
        kind: Secret
        type: Opaque
        metadata:
          name: htpass-secret
          namespace: openshift-config
        data:
          htpasswd: "{{ lookup('file',users_htpasswd) | b64encode }}"

